version: '3.7'
services:
  web:
    build:
      context: .
    container_name: Wallet
    command: ./entrypoint.sh

    volumes:
      -  .:/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - /data/postgres:/app/data
    env_file:
      - .env
  rabbit:
    image: rabbitmq:3.10.7-management-alpine
    restart: always
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
  celery:
    build:
      context: .
    command: celery -A core worker -l info --loglevel=INFO
    depends_on:
      - db
      - rabbit
      - web
    restart: on-failure
  # flower for celery
  flower:
    build:
      context: .
    ports:
      - "5566:5566"
    command: celery -A core flower  --address=0.0.0.0 --port=5566
    depends_on:
      - celery
volumes:
  postgres_data:
