# Generated by Django 4.1.3 on 2022-11-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_organization_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='income',
            field=models.BooleanField(default=False, verbose_name='Income'),
        ),
    ]
