# Generated by Django 4.1.3 on 2022-11-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_categories_user_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
