# Generated by Django 4.1.3 on 2022-11-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_categories_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
    ]
